const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.video,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare
	];
};
self.C3_JsPropNameTable = [
	{М1Фон14Фев: 0},
	{М1ТКИгратьФев: 0},
	{М2ФонФев: 0},
	{М2ТекстФев: 0},
	{М2КОнаФев: 0},
	{М2ККоннектФев: 0},
	{М2КОнФев: 0},
	{М2ТКОнаФев: 0},
	{М2ТКОнФев: 0},
	{М2ТККоннектФЕв: 0},
	{М3ФонФев: 0},
	{М3ТекстФев: 0},
	{М3ЗаголовокФЕВ: 0},
	{М3КИгратьФЕВ: 0},
	{М3ТКИгратьФЕВ: 0},
	{М4ФонФев: 0},
	{М4ЗаголовокФЕВ: 0},
	{М4ТекстФев: 0},
	{М4КИгратьФЕВ: 0},
	{М4ТКИгратьФЕВ: 0},
	{М5ФонФев: 0},
	{М5ЗаголовокФЕВ: 0},
	{М5ТекстФев: 0},
	{М5КИгратьФЕВ: 0},
	{М5ТКИгратьФЕВ: 0},
	{М6ФонФЕВ: 0},
	{DO: 0},
	{М6ДО1ФЕВ: 0},
	{М6ДО2ФЕВ: 0},
	{М6ДО3ФЕВ: 0},
	{М6ДО4ФЕВ: 0},
	{М6ДО0ФЕВ: 0},
	{М6ККОкФЕВ: 0},
	{М6ТКОкФев: 0},
	{М6ВопросФЕВ: 0},
	{М6букет: 0},
	{М6посуда: 0},
	{М6подарок: 0},
	{М6пирожное: 0},
	{М6Сит1ФЕВ: 0},
	{М6Сит2ФЕВ: 0},
	{М6Сит3ФЕВ: 0},
	{М6Сит4ФЕВ: 0},
	{М6пляж: 0},
	{М6горы: 0},
	{М6город: 0},
	{М6природа: 0},
	{М6обнять: 0},
	{М6одна: 0},
	{М6переключиться: 0},
	{М6поговорить: 0},
	{М6худи: 0},
	{М6модно: 0},
	{М6романтика: 0},
	{М6эклектика: 0},
	{М6эстетика: 0},
	{М6салат: 0},
	{М6пельмени: 0},
	{М6сладкое: 0},
	{М6подарки: 0},
	{М6забота: 0},
	{М6слова: 0},
	{М6время: 0},
	{М7ФонФЕВ: 0},
	{М7ДО0ФЕВ: 0},
	{М7ВопросФЕВ: 0},
	{М7ККОкФЕВ: 0},
	{М7ТКОкФев: 0},
	{М7ДО1ФЕВ: 0},
	{М7ДО2ФЕВ: 0},
	{М7ДО3ФЕВ: 0},
	{М7ДО4ФЕВ: 0},
	{М7Сит1ФЕВ: 0},
	{М7Сит2ФЕВ: 0},
	{М7Сит3ФЕВ: 0},
	{М7Сит4ФЕВ2: 0},
	{М7Игры: 0},
	{М7Друзья: 0},
	{М7прогулка: 0},
	{М7СмотритКино: 0},
	{М7Бургер: 0},
	{М7пицца: 0},
	{М7мясо: 0},
	{м7салат: 0},
	{М7музыку: 0},
	{М7Один: 0},
	{М7Поговорит: 0},
	{М7Делом: 0},
	{М7Футбик: 0},
	{М7Танчики: 0},
	{М7Стрим: 0},
	{М7стул: 0},
	{М7Слова: 0},
	{М7Объятия: 0},
	{М7время: 0},
	{М7Забота: 0},
	{М7Шутит: 0},
	{М7слушает: 0},
	{м7инициатива: 0},
	{М7ПоДелу: 0},
	{М8ФонФЕВ: 0},
	{М8ДО0ФЕВ: 0},
	{М8ВопросФЕВ: 0},
	{М8КНЕТФЕВ: 0},
	{М8ТКНЕТФев: 0},
	{Видео: 0},
	{М8азия: 0},
	{М8италия: 0},
	{М8ДОЛевое: 0},
	{М8ДОправое: 0},
	{М8Сит1: 0},
	{М8Сит2: 0},
	{М8ДО1ФЕВ: 0},
	{М8ДО2ФЕВ: 0},
	{М8Связь1: 0},
	{М8Связь2: 0},
	{М8ТКОкФев2: 0},
	{М8Связь3: 0},
	{М8Связь4: 0},
	{М8Связь5: 0},
	{М8Связь6: 0},
	{М8Связь7: 0},
	{М8опера: 0},
	{М8балет: 0},
	{М8черника: 0},
	{М8малина: 0},
	{М8ДиванОбычный: 0},
	{М8ДиванНеобычный: 0},
	{М8Красные: 0},
	{М8Белые: 0},
	{М8гости: 0},
	{М8одни: 0},
	{М8город: 0},
	{М8загород: 0},
	{М8спать: 0},
	{м8гулять: 0},
	{М8вело: 0},
	{М8пляж: 0},
	{М8безПлана: 0},
	{М8план: 0},
	{М8нет: 0},
	{М8собака: 0},
	{М8НаОтпуск: 0},
	{М8НаКвартиру: 0},
	{М8Семйная: 0},
	{М8Спортивная: 0},
	{М8Тайланд: 0},
	{М8Турция: 0},
	{М8ФонФЕВВЫБОР: 0},
	{М8ДО0ФЕВ2: 0},
	{М8СовпалиФЕВ: 0},
	{М8КДАЕВ: 0},
	{М8ТКДаФев: 0},
	{М9ФонФев: 0},
	{М9ТекстФев: 0},
	{М9ЗаголовокФЕВ: 0},
	{М10ТОчкиОн: 0},
	{М10ТОчкиОна: 0},
	{М9ТекстФев4: 0},
	{М9КБонусФЕВ: 0},
	{М9ТКБонусФЕВ: 0},
	{М10ФонФЕв: 0},
	{М10ДО2ФЕВ: 0},
	{М10ДОФЕв: 0},
	{М10ЗаголовокФЕВ: 0},
	{М10ОчкиОнФев: 0},
	{М10ОчкиОнаФЕВ: 0},
	{М10ТЕеОчки: 0},
	{М10ТЕгоОчки: 0},
	{М10ТекстФев: 0},
	{Мышь: 0},
	{М2ФонФев2: 0},
	{М2ТекстФев2: 0},
	{М2КОкФЕВ: 0},
	{М2ТКОкФЕВ: 0},
	{М2ДОФЕВ: 0},
	{М6ФонФЕВ2: 0},
	{М6ДО0ФЕВ2: 0},
	{М6ККОкФЕВ2: 0},
	{М6ТКОкФев2: 0},
	{М5ВопросФЕВ2: 0},
	{М6ФонФЕВ3: 0},
	{М6ДО0ФЕВ3: 0},
	{М5ВопросФЕВ3: 0},
	{М6ККОкФЕВ3: 0},
	{М6ТКОкФев3: 0},
	{М6ПроверкаЕгоОчки: 0},
	{м6проверкакорректности: 0},
	{ПроверкаОна1: 0},
	{ПроверкаОна2: 0},
	{ПроверкаОна3: 0},
	{ПроверкаОна4: 0},
	{ПроверкаОна5: 0},
	{ПроверкаОна6: 0},
	{ПроверкаОн1: 0},
	{ПроверкаОн2: 0},
	{ПроверкаОн3: 0},
	{ПроверкаОн4: 0},
	{ПроверкаОн5: 0},
	{ПроверкаОн6: 0},
	{М7ФонФЕВ2: 0},
	{М7ДО0ФЕВ2: 0},
	{М7ВопросФЕВ2: 0},
	{М7ККОкФЕВ2: 0},
	{М7ТКОкФев2: 0},
	{М7ФонФЕВ3: 0},
	{М7ДО0ФЕВ3: 0},
	{М7ВопросФЕВ3: 0},
	{М7ККОкФЕВ3: 0},
	{М7ТКОкФев3: 0},
	{М7ПроверкаОн1: 0},
	{М7ПроверкаОн2: 0},
	{М7ПроверкаОн3: 0},
	{М7ПроверкаОн4: 0},
	{М7ПроверкаОн5: 0},
	{М7ПроверкаОн6: 0},
	{М7ПроверкаОна1: 0},
	{М7ПроверкаОна2: 0},
	{М7ПроверкаОна3: 0},
	{М7ПроверкаОна4: 0},
	{М7ПроверкаОна5: 0},
	{М7ПроверкаОна6: 0},
	{М7ПроверкаОбщая: 0},
	{хелп1: 0},
	{хелп2: 0},
	{хелп3: 0},
	{хелп4: 0},
	{хелп5: 0},
	{хелп6: 0},
	{м7общиеБаллы: 0},
	{Аудио: 0},
	{Тач: 0},
	{М6ВопросыУгадайЕё: 0},
	{М6Вопрос1ОнаВыбрала: 0},
	{М6Вопрос2ОнаВыбрала: 0},
	{М6Вопрос3ОнаВыбрала: 0},
	{М6Вопрос4ОнаВыбрала: 0},
	{М6Вопрос5ОнаВыбрала: 0},
	{М6Вопрос6ОнаВыбрала: 0},
	{М6Вопрос1ПареньВыбрал: 0},
	{М6Вопрос2ПареньВыбрал: 0},
	{М6Вопрос3ПареньВыбрал: 0},
	{М6Вопрос4ПареньВыбрал: 0},
	{М6Вопрос5ПареньВыбрал: 0},
	{М6Вопрос6ПареньВыбрал: 0},
	{М6ОчкиНабралОн: 0},
	{М6НабралОнВопрос1: 0},
	{М6НабралОнВопрос2: 0},
	{М6НабралОнВопрос3: 0},
	{М6НабралОнВопрос4: 0},
	{М6НабралОнВопрос5: 0},
	{М6НабралОнВопрос6: 0},
	{СНейИграли: 0},
	{М7ВопросыУгадайЕго: 0},
	{М7Вопрос1ОнВыбрал: 0},
	{М7Вопрос2ОнВыбрал: 0},
	{М7Вопрос3ОнВыбрал: 0},
	{М7Вопрос4ОнВыбрал: 0},
	{М7Вопрос5ОнВыбрал: 0},
	{М7Вопрос6ОнВыбрал: 0},
	{М7Вопрос1ДевушкаВыбрала: 0},
	{М7Вопрос2ДевушкаВыбрала: 0},
	{М7Вопрос3ДевушкаВыбрала: 0},
	{М7Вопрос4ДевушкаВыбрала: 0},
	{М7Вопрос5ДевушкаВыбрала: 0},
	{М7Вопрос6ДевушкаВыбрала: 0},
	{М7НабралаОнаВопрос1: 0},
	{М7НабралаОнаВопрос2: 0},
	{М7НабралаОнаВопрос3: 0},
	{М7НабралаОнаВопрос4: 0},
	{М7НабралаОнаВопрос5: 0},
	{М7НабралаОнаВопрос6: 0},
	{СНимИграли: 0},
	{М7ОчкиНабралаОна: 0},
	{м10ОбщиеБаллы: 0}
];

self.InstanceType = {
	М1Фон14Фев: class extends self.ISpriteInstance {},
	М1ТКИгратьФев: class extends self.ITextInstance {},
	М2ФонФев: class extends self.ISpriteInstance {},
	М2ТекстФев: class extends self.ITextInstance {},
	М2КОнаФев: class extends self.ISpriteInstance {},
	М2ККоннектФев: class extends self.ISpriteInstance {},
	М2КОнФев: class extends self.ISpriteInstance {},
	М2ТКОнаФев: class extends self.ITextInstance {},
	М2ТКОнФев: class extends self.ITextInstance {},
	М2ТККоннектФЕв: class extends self.ITextInstance {},
	М3ФонФев: class extends self.ISpriteInstance {},
	М3ТекстФев: class extends self.ITextInstance {},
	М3ЗаголовокФЕВ: class extends self.ITextInstance {},
	М3КИгратьФЕВ: class extends self.ISpriteInstance {},
	М3ТКИгратьФЕВ: class extends self.ITextInstance {},
	М4ФонФев: class extends self.ISpriteInstance {},
	М4ЗаголовокФЕВ: class extends self.ITextInstance {},
	М4ТекстФев: class extends self.ITextInstance {},
	М4КИгратьФЕВ: class extends self.ISpriteInstance {},
	М4ТКИгратьФЕВ: class extends self.ITextInstance {},
	М5ФонФев: class extends self.ISpriteInstance {},
	М5ЗаголовокФЕВ: class extends self.ITextInstance {},
	М5ТекстФев: class extends self.ITextInstance {},
	М5КИгратьФЕВ: class extends self.ISpriteInstance {},
	М5ТКИгратьФЕВ: class extends self.ITextInstance {},
	М6ФонФЕВ: class extends self.ISpriteInstance {},
	М6ДО1ФЕВ: class extends self.ISpriteInstance {},
	М6ДО2ФЕВ: class extends self.ISpriteInstance {},
	М6ДО3ФЕВ: class extends self.ISpriteInstance {},
	М6ДО4ФЕВ: class extends self.ISpriteInstance {},
	М6ДО0ФЕВ: class extends self.ISpriteInstance {},
	М6ККОкФЕВ: class extends self.ISpriteInstance {},
	М6ТКОкФев: class extends self.ITextInstance {},
	М6ВопросФЕВ: class extends self.ITextInstance {},
	М6букет: class extends self.ISpriteInstance {},
	М6посуда: class extends self.ISpriteInstance {},
	М6подарок: class extends self.ISpriteInstance {},
	М6пирожное: class extends self.ISpriteInstance {},
	М6Сит1ФЕВ: class extends self.ITextInstance {},
	М6Сит2ФЕВ: class extends self.ITextInstance {},
	М6Сит3ФЕВ: class extends self.ITextInstance {},
	М6Сит4ФЕВ: class extends self.ITextInstance {},
	М6пляж: class extends self.ISpriteInstance {},
	М6горы: class extends self.ISpriteInstance {},
	М6город: class extends self.ISpriteInstance {},
	М6природа: class extends self.ISpriteInstance {},
	М6обнять: class extends self.ISpriteInstance {},
	М6одна: class extends self.ISpriteInstance {},
	М6переключиться: class extends self.ISpriteInstance {},
	М6поговорить: class extends self.ISpriteInstance {},
	М6худи: class extends self.ISpriteInstance {},
	М6модно: class extends self.ISpriteInstance {},
	М6романтика: class extends self.ISpriteInstance {},
	М6эклектика: class extends self.ISpriteInstance {},
	М6эстетика: class extends self.ISpriteInstance {},
	М6салат: class extends self.ISpriteInstance {},
	М6пельмени: class extends self.ISpriteInstance {},
	М6сладкое: class extends self.ISpriteInstance {},
	М6подарки: class extends self.ISpriteInstance {},
	М6забота: class extends self.ISpriteInstance {},
	М6слова: class extends self.ISpriteInstance {},
	М6время: class extends self.ISpriteInstance {},
	М7ФонФЕВ: class extends self.ISpriteInstance {},
	М7ДО0ФЕВ: class extends self.ISpriteInstance {},
	М7ВопросФЕВ: class extends self.ITextInstance {},
	М7ККОкФЕВ: class extends self.ISpriteInstance {},
	М7ТКОкФев: class extends self.ITextInstance {},
	М7ДО1ФЕВ: class extends self.ISpriteInstance {},
	М7ДО2ФЕВ: class extends self.ISpriteInstance {},
	М7ДО3ФЕВ: class extends self.ISpriteInstance {},
	М7ДО4ФЕВ: class extends self.ISpriteInstance {},
	М7Сит1ФЕВ: class extends self.ITextInstance {},
	М7Сит2ФЕВ: class extends self.ITextInstance {},
	М7Сит3ФЕВ: class extends self.ITextInstance {},
	М7Сит4ФЕВ2: class extends self.ITextInstance {},
	М7Игры: class extends self.ISpriteInstance {},
	М7Друзья: class extends self.ISpriteInstance {},
	М7прогулка: class extends self.ISpriteInstance {},
	М7СмотритКино: class extends self.ISpriteInstance {},
	М7Бургер: class extends self.ISpriteInstance {},
	М7пицца: class extends self.ISpriteInstance {},
	М7мясо: class extends self.ISpriteInstance {},
	м7салат: class extends self.ISpriteInstance {},
	М7музыку: class extends self.ISpriteInstance {},
	М7Один: class extends self.ISpriteInstance {},
	М7Поговорит: class extends self.ISpriteInstance {},
	М7Делом: class extends self.ISpriteInstance {},
	М7Футбик: class extends self.ISpriteInstance {},
	М7Танчики: class extends self.ISpriteInstance {},
	М7Стрим: class extends self.ISpriteInstance {},
	М7стул: class extends self.ISpriteInstance {},
	М7Слова: class extends self.ISpriteInstance {},
	М7Объятия: class extends self.ISpriteInstance {},
	М7время: class extends self.ISpriteInstance {},
	М7Забота: class extends self.ISpriteInstance {},
	М7Шутит: class extends self.ISpriteInstance {},
	М7слушает: class extends self.ISpriteInstance {},
	м7инициатива: class extends self.ISpriteInstance {},
	М7ПоДелу: class extends self.ISpriteInstance {},
	М8ФонФЕВ: class extends self.ISpriteInstance {},
	М8ДО0ФЕВ: class extends self.ISpriteInstance {},
	М8ВопросФЕВ: class extends self.ITextInstance {},
	М8КНЕТФЕВ: class extends self.ISpriteInstance {},
	М8ТКНЕТФев: class extends self.ITextInstance {},
	Видео: class extends self.IWorldInstance {},
	М8азия: class extends self.ISpriteInstance {},
	М8италия: class extends self.ISpriteInstance {},
	М8ДОЛевое: class extends self.ISpriteInstance {},
	М8ДОправое: class extends self.ISpriteInstance {},
	М8Сит1: class extends self.ITextInstance {},
	М8Сит2: class extends self.ITextInstance {},
	М8ДО1ФЕВ: class extends self.ISpriteInstance {},
	М8ДО2ФЕВ: class extends self.ISpriteInstance {},
	М8Связь1: class extends self.ISpriteInstance {},
	М8Связь2: class extends self.ISpriteInstance {},
	М8ТКОкФев2: class extends self.ITextInstance {},
	М8Связь3: class extends self.ISpriteInstance {},
	М8Связь4: class extends self.ISpriteInstance {},
	М8Связь5: class extends self.ISpriteInstance {},
	М8Связь6: class extends self.ISpriteInstance {},
	М8Связь7: class extends self.ISpriteInstance {},
	М8опера: class extends self.ISpriteInstance {},
	М8балет: class extends self.ISpriteInstance {},
	М8черника: class extends self.ISpriteInstance {},
	М8малина: class extends self.ISpriteInstance {},
	М8ДиванОбычный: class extends self.ISpriteInstance {},
	М8ДиванНеобычный: class extends self.ISpriteInstance {},
	М8Красные: class extends self.ISpriteInstance {},
	М8Белые: class extends self.ISpriteInstance {},
	М8гости: class extends self.ISpriteInstance {},
	М8одни: class extends self.ISpriteInstance {},
	М8город: class extends self.ISpriteInstance {},
	М8загород: class extends self.ISpriteInstance {},
	М8спать: class extends self.ISpriteInstance {},
	м8гулять: class extends self.ISpriteInstance {},
	М8вело: class extends self.ISpriteInstance {},
	М8пляж: class extends self.ISpriteInstance {},
	М8безПлана: class extends self.ISpriteInstance {},
	М8план: class extends self.ISpriteInstance {},
	М8нет: class extends self.ISpriteInstance {},
	М8собака: class extends self.ISpriteInstance {},
	М8НаОтпуск: class extends self.ISpriteInstance {},
	М8НаКвартиру: class extends self.ISpriteInstance {},
	М8Семйная: class extends self.ISpriteInstance {},
	М8Спортивная: class extends self.ISpriteInstance {},
	М8Тайланд: class extends self.ISpriteInstance {},
	М8Турция: class extends self.ISpriteInstance {},
	М8ФонФЕВВЫБОР: class extends self.ISpriteInstance {},
	М8ДО0ФЕВ2: class extends self.ISpriteInstance {},
	М8СовпалиФЕВ: class extends self.ITextInstance {},
	М8КДАЕВ: class extends self.ISpriteInstance {},
	М8ТКДаФев: class extends self.ITextInstance {},
	М9ФонФев: class extends self.ISpriteInstance {},
	М9ТекстФев: class extends self.ITextInstance {},
	М9ЗаголовокФЕВ: class extends self.ITextInstance {},
	М10ТОчкиОн: class extends self.ITextInstance {},
	М10ТОчкиОна: class extends self.ITextInstance {},
	М9ТекстФев4: class extends self.ITextInstance {},
	М9КБонусФЕВ: class extends self.ISpriteInstance {},
	М9ТКБонусФЕВ: class extends self.ITextInstance {},
	М10ФонФЕв: class extends self.ISpriteInstance {},
	М10ДО2ФЕВ: class extends self.ISpriteInstance {},
	М10ДОФЕв: class extends self.ISpriteInstance {},
	М10ЗаголовокФЕВ: class extends self.ITextInstance {},
	М10ОчкиОнФев: class extends self.ISpriteInstance {},
	М10ОчкиОнаФЕВ: class extends self.ISpriteInstance {},
	М10ТЕеОчки: class extends self.ITextInstance {},
	М10ТЕгоОчки: class extends self.ITextInstance {},
	М10ТекстФев: class extends self.ITextInstance {},
	Мышь: class extends self.IInstance {},
	М2ФонФев2: class extends self.ISpriteInstance {},
	М2ТекстФев2: class extends self.ITextInstance {},
	М2КОкФЕВ: class extends self.ISpriteInstance {},
	М2ТКОкФЕВ: class extends self.ITextInstance {},
	М2ДОФЕВ: class extends self.ISpriteInstance {},
	М6ФонФЕВ2: class extends self.ISpriteInstance {},
	М6ДО0ФЕВ2: class extends self.ISpriteInstance {},
	М6ККОкФЕВ2: class extends self.ISpriteInstance {},
	М6ТКОкФев2: class extends self.ITextInstance {},
	М5ВопросФЕВ2: class extends self.ITextInstance {},
	М6ФонФЕВ3: class extends self.ISpriteInstance {},
	М6ДО0ФЕВ3: class extends self.ISpriteInstance {},
	М5ВопросФЕВ3: class extends self.ITextInstance {},
	М6ККОкФЕВ3: class extends self.ISpriteInstance {},
	М6ТКОкФев3: class extends self.ITextInstance {},
	М6ПроверкаЕгоОчки: class extends self.ITextInstance {},
	м6проверкакорректности: class extends self.ITextInstance {},
	ПроверкаОна1: class extends self.ITextInstance {},
	ПроверкаОна2: class extends self.ITextInstance {},
	ПроверкаОна3: class extends self.ITextInstance {},
	ПроверкаОна4: class extends self.ITextInstance {},
	ПроверкаОна5: class extends self.ITextInstance {},
	ПроверкаОна6: class extends self.ITextInstance {},
	ПроверкаОн1: class extends self.ITextInstance {},
	ПроверкаОн2: class extends self.ITextInstance {},
	ПроверкаОн3: class extends self.ITextInstance {},
	ПроверкаОн4: class extends self.ITextInstance {},
	ПроверкаОн5: class extends self.ITextInstance {},
	ПроверкаОн6: class extends self.ITextInstance {},
	М7ФонФЕВ2: class extends self.ISpriteInstance {},
	М7ДО0ФЕВ2: class extends self.ISpriteInstance {},
	М7ВопросФЕВ2: class extends self.ITextInstance {},
	М7ККОкФЕВ2: class extends self.ISpriteInstance {},
	М7ТКОкФев2: class extends self.ITextInstance {},
	М7ФонФЕВ3: class extends self.ISpriteInstance {},
	М7ДО0ФЕВ3: class extends self.ISpriteInstance {},
	М7ВопросФЕВ3: class extends self.ITextInstance {},
	М7ККОкФЕВ3: class extends self.ISpriteInstance {},
	М7ТКОкФев3: class extends self.ITextInstance {},
	М7ПроверкаОн1: class extends self.ITextInstance {},
	М7ПроверкаОн2: class extends self.ITextInstance {},
	М7ПроверкаОн3: class extends self.ITextInstance {},
	М7ПроверкаОн4: class extends self.ITextInstance {},
	М7ПроверкаОн5: class extends self.ITextInstance {},
	М7ПроверкаОн6: class extends self.ITextInstance {},
	М7ПроверкаОна1: class extends self.ITextInstance {},
	М7ПроверкаОна2: class extends self.ITextInstance {},
	М7ПроверкаОна3: class extends self.ITextInstance {},
	М7ПроверкаОна4: class extends self.ITextInstance {},
	М7ПроверкаОна5: class extends self.ITextInstance {},
	М7ПроверкаОна6: class extends self.ITextInstance {},
	М7ПроверкаОбщая: class extends self.ITextInstance {},
	хелп1: class extends self.ITextInstance {},
	хелп2: class extends self.ITextInstance {},
	хелп3: class extends self.ITextInstance {},
	хелп4: class extends self.ITextInstance {},
	хелп5: class extends self.ITextInstance {},
	хелп6: class extends self.ITextInstance {},
	м7общиеБаллы: class extends self.ITextInstance {},
	Аудио: class extends self.IInstance {},
	Тач: class extends self.IInstance {}
}